version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    image: ${NODEJS_BACK_IMAGE_NAME}
    container_name: ${NODEJS_BACK_CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    ports:
      - ${BACK_APP_EXTERNAL_PORT}:8080
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon app.js
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    image: ${POSTGRES_BACK_IMAGE_NAME}
    container_name: ${POSTGRES_BACK_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
    driver: local
  postgres_data:
    driver: local